### ISSUE TITLE
Python Errors

### ISSUE THREAD

**Issue by n8091977** [alsmith/multicast-relay#12]
Hello,

I am struggling to get this running having tried both Ubuntu 14.04 and 16.10. I have installed netifaces but am unsure as to what the error is:

multicast@multicast-manage:~/multicast-relay$ python -V
Python 2.7.6
multicast@multicast-manage:~/multicast-relay$ pip install netifaces
Requirement already satisfied (use --upgrade to upgrade): netifaces in /usr/lib/python2.7/dist-packages
Cleaning up...
multicast@multicast-manage:~/multicast-relay$

multicast@multicast-manage:~/multicast-relay$ sudo ./multicast-relay.py --interfaces eth1 eth3 --foreground
^CTraceback (most recent call last):
  File "./multicast-relay.py", line 447, in <module>
    sys.exit(main())
  File "./multicast-relay.py", line 444, in main
    packetRelay.loop()
  File "./multicast-relay.py", line 168, in loop
    (inputready, _, _) = select.select(self.receivers, [], [])
KeyboardInterrupt

**Comment by alsmith** [comment]
Try also adding `--verbose` to see information as to what packets are being relayed.

As far as I can make out, the error here is merely the python traceback in response to `Ctrl-C` being pressed. Without `--foreground` the relay will simply fork itself in the background and keep itself quiet. But with `--foreground` it will appear to just hang (intended behaviour). Adding `--verbose` will encourage it to tell you more as to what it's up to.

If you're having trouble with it not relaying packets correctly, maybe the output after adding `--verbose` would help, along with `ifconfig eth1` and `ifconfig eth3` and a description of where your devices are, i.e. on which networks. Thanks!

**Comment by alsmith** [comment]
Closing due to inactivity.
