### ISSUE TITLE
Breaking update for --listen 

### ISSUE THREAD

**Issue by mojo333** [alsmith/multicast-relay#66]
Just pulled the latest version which added changes for --listen. Unfortunately this option is now mandatory otherwise you see the following error as there is no check to see if the argument is being supplied in the 1st place:

```
[UDM] root@udmp:/mnt/data/containers# podman run --network=host --name ssdp-relay --restart=always -e INTERFACES="br50 b
r99" -e OPTS="" localhost/multicast-relay
Starting multicast-relay on  Mon May 2 16:52:34 UTC 2022
Using Interfaces: br50 br99
Using Options --foreground
Traceback (most recent call last):
  File "//./multicast-relay/multicast-relay.py", line 1028, in <module>
    sys.exit(main())
  File "//./multicast-relay/multicast-relay.py", line 967, in main
    packetRelay = PacketRelay(interfaces           = args.interfaces,
  File "//./multicast-relay/multicast-relay.py", line 208, in __init__
    for addr in listen:
TypeError: 'NoneType' object is not iterable
```
Adding in the --listen argument with a random IP bypasses the issue.

**Comment by alsmith** [comment]
Ah thanks - sorry about that! Fixed !

**Comment by mojo333** [comment]
Thanks for the quick fix. All working as expected.
